name: Code Coverage

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@feat/test-dep-hooks
    secrets: inherit
    with:
      espeak_ng_version: '1.52.0'
      python_version: '3.11'
      coverage_source: 'espyak'
      test_path: 'test/'
      install_extras: '-e .[test]'
      min_coverage: 0
